export enum Configuration {
	PORT = "PORT",
	HOST = "HOST",
	USERNAME = "USERNAME",
	PASSWORD = "PASSWORD",
	DATABASE = "DATABASE",
	DATABASE_URL = "DATABASE_URL",
	DATABASE_PORT = "DATABASE_PORT",
	JWT_SECRET = "JWT_SECRET",
}
